### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by genjeetv** [OpsecGuy/BetterGo#28]
in the video the guy opened cmd, wrote pip and then the video clipped and then opened a new cmd with the file path starting in the cheat folder. I have no clue how to do this since im new to this code shit. please someone help

**Comment by tankow79** [comment]
Open the BetterGo-main folder
![NVIDIA_Share_6gKVsQwH7W](https://user-images.githubusercontent.com/59967596/229958396-659000cc-e44a-4cc0-bb54-01d125f2731c.png)
Write "cmd" in my case instead of "D:\Desktop\BetterGo-main" press enter
![NVIDIA_Share_XBVPHYPpA6](https://user-images.githubusercontent.com/59967596/229958785-db553b81-3edd-42a5-95bb-39beb30bd2cd.png)
became
![NVIDIA_Share_mGk3kFkHSj](https://user-images.githubusercontent.com/59967596/229958899-74be6adf-10ac-4b0e-bb3b-b38fdb36f7e2.png)
![cmd_U4wGiiPMTV](https://user-images.githubusercontent.com/59967596/229959066-2b827474-bd28-422b-b92e-2b2f1bcef474.png)
Here is your window, then repeat everything from the video
Good luck !
